spring:
  # TODO modify the configuration
  rabbitmq:
    host: 192.168.159.134
    port: 5672
    username: dhx
    password: qwer
    virtual-host: /

spark:
  appId: 6681eae7
  apiKey: 11111111
  apiSecret: 111111111111111
  modelVersion: 3
  defaultHostInfo:
    host: spark-api.xf-yun.com
    path: /v3.1/chat
    domain: generalv3
  hostInfos:
    - host: spark-api.xf-yun.com
      path: /v1.1/chat
      domain: general
    - host: spark-api.xf-yun.com
      path: /v2.1/chat
      domain: generalv2
    - host: spark-api.xf-yun.com
      path: /v3.1/chat
      domain: generalv3

knife4j:
  enable: true
  openapi:
    title: demo_backend
    description: 后端接口文档
    email: dhx2648466390@163.com
    concat: adorabled4
    url: https://blog.dhx.icu
    version: v4.0
    license: Apache 2.0
    license-url: https://blog.dhx.icu
    terms-of-service-url: https://blog.dhx.icu
    group:
      dev:
        group-name: 开发环境
        api-rule: package
        api-rule-resources:
          - com.dhx.dem0828
      prod:
        group-name: 线上环境
        api-rule: package
        api-rule-resources:
          - com.dhx.dem0828